CREATE TABLE users(
	id SERIAL PRIMARY KEY,
	user_name VARCHAR(100),
	password TEXT,
	createdAT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updatedAT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)
CREATE TABLE product_category(
	id SERIAL PRIMARY KEY,
	name VARCHAR (100),
	description VARCHAR(200),
	createdAT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updatedAT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE customer(
	id SERIAL PRIMARY KEY,
	firstname VARCHAR(100),
	lastname VARCHAR(100),
	user_id INTEGER REFERENCES users(id),
	createdAT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updatedAT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)
CREATE TABLE orders(
	id SERIAL PRIMARY KEY,
	user_id INTEGER REFERENCES users(id),
	totalproduct INT,
	totalprice NUMERIC,
	createdAT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updatedAT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)
CREATE TABLE product(	
	id SERIAL PRIMARY KEY,
	name VARCHAR(100),
	description VARCHAR(200),
	category_id INTEGER REFERENCES product_category(id),
	price NUMERIC,
	image VARCHAR(200),
	createdAT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updatedAT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)
CREATE TABLE order_detail(	
	id SERIAL PRIMARY KEY,
	order_id INTEGER REFERENCES orders(id),
	product_id INTEGER REFERENCES product(id),
	createdAT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updatedAT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)